name: bump-version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of semgrep to use"
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Authenticate as semgrep-ide-plugins-release
        id: generate-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ vars.SEMGREP_IDE_PLUGINS_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMGREP_IDE_PLUGINS_RELEASE_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: lts/*
      - name: Update version
        env:
          SEMGREP_STATIC_VERSION: "release-${{ inputs.version }}"
        run: |
          echo "${SEMGREP_STATIC_VERSION}" > semgrep-version
      - name: Bump package patch version
        run: npm version patch --no-git-tag-version
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          branch: gha/bump-version-${{ inputs.version }}-${{ github.run_id }}-${{ github.run_attempt }}
          commit-message: "Bump semgrep to ${{ inputs.version }}"
          title: "chore: Release Version ${{ inputs.version }}"
          body: "Bump Semgrep Version to ${{ inputs.version }}"
