name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  # Running pre-commit in CI via the shared reusable workflow. See
  # .pre-commit-config.yaml for our pre-commit configuration.
  # Dogfood: we run Semgrep inside pre-commit, so this also tests how
  # semgrep interacts with pre-commit.
  pre-commit:
    uses: semgrep/release-workflows/.github/workflows/pre-commit.yaml@c04907222197635bc8fc0d80b1d5fec8f945eb43 # develop
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
        with:
          fail_on_error: true
